<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<small>Loading &hellip;</small>' => '',
    'Actions' => 'Acțiuni',
    'Active' => 'Activ',
    'Add Book' => 'Adaugă carte',
    'All' => 'Tot',
    'Are you sure to delete this {item}?' => 'Ești sigur că vrei să ștergi această {item}?',
    'Book Listing' => 'Lista',
    'CSV' => 'CSV',
    'Clear selection' => 'Golește selecția',
    'Collapse' => 'Colapsează',
    'Collapse All' => 'Colapsează tot',
    'Comma Separated Values' => 'Valori separate prin virgulă',
    'Delete' => 'Șterge',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Dezactivează blocatoarele de ferestre pop-up din browser pentru a asigura descărcarea corectă.',
    'Download Selected' => 'Descarcă selecția',
    'Excel' => 'Excel',
    'Expand' => 'Extinde',
    'Expand All' => 'Extinde tot',
    'Export' => 'Exportă',
    'Export All Data' => 'Exportă toate datele',
    'Export Page Data' => 'Exportă datele din pagină',
    'ExportWorksheet' => 'Exportă foaia de lucru',
    'Failed to update editable data due to an unknown server error' => 'Eroare la actualizarea datelor editabile din cauza unei erori de server necunoscute.',
    'Generated' => 'Generat',
    'Generating the export file. Please wait...' => 'Se generează fișierul de export. Așteaptă...',
    'Grid Export' => 'Export tabel',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Hyper Text Markup Language',
    'Inactive' => 'Inactiv',
    'Invalid editable index or model form name' => 'Index editabil sau nume formular model invalid',
    'Invalid or bad editable data' => 'Date editabile invalide sau greșite',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript Object Notation',
    'Krajee Solutions' => '',
    'Krajee Yii2 Grid Export Extension' => '',
    'Library' => 'Librărie',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Nu s-au găsit date',
    'No valid editable model found' => 'Nu s-a găsit un model editabil valid',
    'Ok to proceed?' => 'Sigur dorești să continui?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => '',
    'Page' => 'Pagină',
    'Portable Document Format' => 'Format de document portabil',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Cererea a fost trimisă! Poți închide în siguranță acest dialog după ce ai salvat fișierul descărcat.',
    'Reset Grid' => 'Resetează tabelul',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Redimensionează coloanele tabelului la fel ca într-o foaie de calcul, trăgând marginile coloanelor.',
    'Select...' => '',
    'Show all data' => 'Afișează toate datele',
    'Show first page data' => 'Afișează datele primei pagini',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.' => 'Se afișează <b>{begin, number}-{end, number}</b> din <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.',
    'Tab Delimited Text' => 'Text delimitat prin tab',
    'Text' => 'Text',
    'The CSV export file will be generated for download.' => 'Fișierul de export CSV va fi generat pentru descărcare.',
    'The EXCEL export file will be generated for download.' => 'Fișierul de export EXCEL va fi generat pentru descărcare.',
    'The HTML export file will be generated for download.' => 'Fișierul de export HTML va fi generat pentru descărcare.',
    'The JSON export file will be generated for download.' => 'Fișierul de export JSON va fi generat pentru descărcare.',
    'The PDF export file will be generated for download.' => 'Fișierul de export PDF va fi generat pentru descărcare.',
    'The TEXT export file will be generated for download.' => 'Fișierul de export TEXT va fi generat pentru descărcare.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Rezumatul paginii afișează SUMA pentru primele 3 coloane de sume și MEDIA pentru ultima.',
    'The table header sticks to the top in this demo as you scroll' => 'Antetul tabelului rămâne fix în partea de sus în această demonstrație în timp ce derulezi.',
    'There are {totalCount} records. Are you sure you want to display them all?' => 'Există {totalCount} înregistrări. Sigur vrei să le afișezi pe toate?',
    'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.' => 'Total <b>{count, number}</b> {count, plural, one{{item}} other{{items}}}.',
    'Update' => 'Actualizează',
    'View' => 'Vizualizează',
    'Yii2 Grid Export (PDF)' => '',
    'export' => 'export',
    'grid-export' => 'export-tabel',
    'item' => 'înregistrare',
    'items' => 'înregistrări',
    'items-acc' => 'înregistrare',
    'items-few' => 'înregistrări',
    'items-many' => 'de înregistrări',
    'krajee, grid, export, yii2-grid, pdf' => ' ',
    '© Krajee Yii2 Extensions' => ' ',
];
